### ISSUE TITLE
File Size

### ISSUE THREAD

**Issue by iagocanalejas** [codingjoe/django-stdimage#192]
Hi, first of all nice library, i wanna ask if it's possible to retrieve generated file size in some place, i have a signal to compute and save my image size but i can't find the variations size.

```python
def compute_size(instance, raw, **kwargs):
    if hasattr(instance, 'image') and instance.image and not raw:  # Required check for tests and fixtures
        user = instance.exercise.created_by if isinstance(instance, ExerciseImage) else instance.comment.user
        total_size = instance.image.size
        if hasattr(instance.image, 'variations'):  # Never runs
            for variation in instance.image.variations:
                total_size += variation.size
```

**Comment by marojenka** [comment]
hi,
As I see it `image` indeed don't have variations attribute, it can be found in field: `image.field.variations`.
hence, skipping error handling and stuff you might be looking for something like this:
```python
for variation in instance.image.field.variations:
    total_size += getattr(instance.image, 'large').size()
```

**Comment by iagocanalejas** [comment]
Ok so, that solves the non existing `variations` bue now the problem is that the file is created after the signal runs so i can call `.size()` on it.

```python
def compute_size(instance, raw, **kwargs):
    if hasattr(instance, 'image') and instance.image and not raw:  # Required check for tests and fixtures
        total_size = instance.image.size
        if hasattr(instance.image, 'field') and hasattr(instance.image.field, 'variations'):
            for variation in instance.image.field.variations:
                total_size += getattr(instance.image, variation).size()
```

```sh
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'file_path'
```

**Comment by marojenka** [comment]
are you using post_save signal?

**Comment by iagocanalejas** [comment]
Yep

```python
@receiver(post_save, sender=ModelName)
```

**Comment by marojenka** [comment]
right. 
I made two mistakes in two lines above, sorry, it was an idea, should've fully checked it.
This is working for me:
```python
 for variation, _ in instance.image.field.variations.items():
     total_size += getattr(instance.image, variation).size
```

**Comment by iagocanalejas** [comment]
Sorry, same error

```python
@receiver(post_save, sender=ModelName)
def compute_size(instance, raw, **kwargs):
    if hasattr(instance, 'image') and instance.image and not raw:  # Required check for tests and fixtures
        total_size = instance.image.size
        if hasattr(instance.image, 'field') and hasattr(instance.image.field, 'variations'):
            for variation, _ in instance.image.field.variations.items():
                total_size += getattr(instance.image, variation).size
```
I also try debugging it but the object only contains errors like:

```sh
 thumbnail = {ImageFieldFile} path/image.png
	_committed = {bool} True
	closed = {bool} True
	_file = {NoneType} None
	 file = {str} 'Traceback (most recent call last):\n  File "C:\\Users\\Canalejas\\AppData\\Local\\JetBrains\\Toolbox\\apps\\PyCharm-P\\ch-0\\181.4203.547\\helpers\\pydev\\_pydevd_bundle\\pydevd_resolver.py", line 166, in _getPyDictionary\n    attr = getattr(var, n)\n  File 
	size = {str} 'Traceback (most recent call last):\n  File "C:\\Users\\Canalejas\\AppData\\Local\\JetBrains\\Toolbox\\apps\\PyCharm-P\\ch-0\\181.4203.547\\helpers\\pydev\\_pydevd_bundle\\pydevd_resolver.py", line 166, in _getPyDictionary\n    attr = getattr(var, n)\n  File 
```

The image is still created even if the signal fail.

**Comment by codingjoe** [comment]
I honestly never tried that. Mostly because the variation size is kind of specified is it not? At least it's max bounds. that being said, you don't have access to the variations at this point, because they did not exist when class was created. Mostly because you are creating a new object.
You would need to call `set_variations` manually. It's usually called in `contribute_to_class` which in tern is called when a Django model is constructed. As I said, not in this particular case.

I hope that helps you, let me know if I can be of more help.
